bg_platform_home:
    path:    /
    defaults: { _controller:BGPlatformBundle:Advert:index}
bg_platform_home01:
    path:	/01
    defaults: { _controller:BGPlatformBundle:Advert:index01}
bg_platform_view:
    path:    /advert/{id}
    defaults: { _controller:BGPlatformBundle:Advert:view}
bg_platform_add:
    path:    /add
    defaults: { _controller:BGPlatformBundle:Advert:add}
bg_platform_view_slug:
    path:    /{year}/{slug}.{_format}
    defaults: { _controller:BGPlatformBundle:Advert:viewSlug, _format: html}
    requirements:
        year: \d{4}
        format: html|xml